# enter 6 number and display only unique number
s = set()

n = input("input a number")
s.add(int(n))
n = input("input a number")
s.add(int(n))
n = input("input a number")
s.add(int(n))
n = input("input a number")
s.add(int(n))
n = input("input a number")
s.add(int(n))
n = input("input a number")
s.add(int(n))
print(s)